stages:
  - src_chk
  - bhv_sim
  - run_syn
  - bit_gen
  - fpga_eval

variables:
    GIT_SUBMODULE_STRATEGY: normal
    GIT_DEPTH: "1"

default:
  image: gitlab.agileserve.org.cn:15050/zelin/vivado-ci-tools/vivado-vnc-ci-multistage:v2.6
  tags: 
    - k8s
  before_script:
    - cd flow

rtl_chk:
  stage: src_chk
  script:
    - make HW_ACT=rtl_chk CI_RUN=y vivado_prj
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/hardware/vivado_out/run_log

conv_compile:
  stage: src_chk
  script:
    - make conv
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/benchmark/conv

01_sw_conv_bhv_sim:
  stage: bhv_sim
  allow_failure: true
  script:
    - make HW_ACT=bhv_sim HW_VAL=conv:01 DUMP_TIME="0 5000000" CI_RUN=y vivado_prj
  timeout: 1 hours
  dependencies:
    - conv_compile
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - flow/hardware/vivado_out/run_log
      - flow/hardware/vivado_out/sim

02_hw_conv_bhv_sim:
  stage: bhv_sim
  allow_failure: true
  script:
    - make HW_ACT=bhv_sim HW_VAL=conv:02 CI_RUN=y vivado_prj
  timeout: 1 hours
  dependencies:
    - conv_compile
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - flow/hardware/vivado_out/run_log
      - flow/hardware/vivado_out/sim

run_syn:
  stage: run_syn
  script:
    - make HW_ACT=run_syn CI_RUN=y vivado_prj
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/hardware/vivado_out/synth_rpt
      - flow/hardware/vivado_out/run_log

bit_gen:
  stage: bit_gen
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - make HW_ACT=bit_gen CI_RUN=y vivado_prj
  timeout: 5 hours
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/hardware/vivado_out/synth_rpt
      - flow/hardware/vivado_out/impl_rpt
      - flow/hw_plat/
      - flow/hardware/vivado_out/run_log

sw_conv_fpga_eval:
  stage: fpga_eval
  variables:
    GIT_STRATEGY: clone
  tags:
    - nf_vm
  script:
    - mkdir -p ./run/log 
    - cd run/
    - bash ci_run.sh $CI_CONCURRENT_ID conv | tee ./log/cloud_run.log
  dependencies:
    - conv_compile 
    - bit_gen
  timeout: 5 hours
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/run/log/
